### ISSUE TITLE
plugin does not play on Kodi Matrix RPi4

### ISSUE THREAD

**Issue by rosede12** [b-pass/plugin.video.the-chosen#4]
I use LibreElec v10.0.4 (Kodi Matrix) on an RPi4.    I just installed the add-on, however it will not play.  Below is output from the logs.

`2023-05-05 08:43:14.504 T:13736   ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'requests.exceptions.SSLError'>
                                                   Error Contents: HTTPSConnectionPool(host='chosen-hydra.vidangel.com', port=443): Max retries exceeded with url: /graphql (Caused by SSLErr
or(CertificateError("hostname 'chosen-hydra.vidangel.com' doesn't match 'prod-b.angelstudios.com'")))
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 703, in urlopen
                                                       httplib_response = self._make_request(
                                                     File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 386, in _make_request
                                                       self._validate_conn(conn)
                                                     File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 1042, in _validate_conn
                                                       conn.connect()
                                                     File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connection.py", line 467, in connect
                                                       _match_hostname(cert, self.assert_hostname or server_hostname)
                                                     File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connection.py", line 540, in _match_hostname
                                                       match_hostname(cert, asserted_hostname)
                                                     File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/util/ssl_match_hostname.py", line 155, in match_hostname
                                                       raise CertificateError("hostname %r doesn't match %r" % (hostname, dnsnames[0]))
                                                   urllib3.util.ssl_match_hostname.CertificateError: hostname 'chosen-hydra.vidangel.com' doesn't match 'prod-b.angelstudios.com'

                                                   During handling of the above exception, another exception occurred:

                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 440, in send
                                                       resp = conn.urlopen(
                                                     File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py", line 787, in urlopen
                                                       retries = retries.increment(
                                                     File "/storage/.kodi/addons/script.module.urllib3/lib/urllib3/util/retry.py", line 592, in increment
                                                       raise MaxRetryError(_pool, url, error or ResponseError(cause))
                                                   urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='chosen-hydra.vidangel.com', port=443): Max retries exceeded with url: /graphql
 (Caused by SSLError(CertificateError("hostname 'chosen-hydra.vidangel.com' doesn't match 'prod-b.angelstudios.com'")))

                                                   During handling of the above exception, another exception occurred:

                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.the-chosen/addon.py", line 209, in <module>
                                                       list_seasons()
                                                     File "/storage/.kodi/addons/plugin.video.the-chosen/addon.py", line 43, in list_seasons
                                                       for season in list_all():
                                                     File "/storage/.kodi/addons/plugin.video.the-chosen/addon.py", line 32, in list_all
                                                       resp = requests.post('https://chosen-hydra.vidangel.com/graphql', json=data)
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/api.py", line 117, in post
                                                       return request('post', url, data=data, json=json, **kwargs)
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/api.py", line 61, in request
                                                       return session.request(method=method, url=url, **kwargs)
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 529, in request
                                                       resp = self.send(prep, **send_kwargs)
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/sessions.py", line 645, in send
                                                       r = adapter.send(request, **kwargs)
                                                     File "/storage/.kodi/addons/script.module.requests/lib/requests/adapters.py", line 517, in send
                                                       raise SSLError(e, request=request)
                                                   requests.exceptions.SSLError: HTTPSConnectionPool(host='chosen-hydra.vidangel.com', port=443): Max retries exceeded with url: /graphql (Ca
used by SSLError(CertificateError("hostname 'chosen-hydra.vidangel.com' doesn't match 'prod-b.angelstudios.com'")))
  -->End of Python script error report<--
`

Thank you

**Comment by b-pass** [comment]
Fixed in 94cb8e2067b8fe7f6ca64f0e1f5d259c66fc2118, I will add a new release to the releases page.  Thanks!
