### ISSUE TITLE
Doe not start

### ISSUE THREAD

**Issue by LuisLlana** [b-pass/plugin.video.the-chosen#8]
I have just downloaded installed the plugin. It gives a register error. I am not very familiar with kodi. I do not know how to provide more information. I attach a screenshot with the information of my system.

![IMG_20240616_100130](https://github.com/b-pass/plugin.video.the-chosen/assets/1461088/e5304dc0-0875-4d66-b9ca-7d7ccef6253c)

**Comment by b-pass** [comment]
Does it happen when you install it, or when you play an episode, or when you first open it after installing? Can you give a screenshot or the text of the error?

**Comment by LuisLlana** [comment]
The error happens when starting the add-on. The error appears in Spanish, in English is somthing like: Revise registry information. May this helps, in order to watch the espisodes in firefox, I have to log in in the platform. Otherwise, a lock appears in the videos.

![IMG_20240617_072355](https://github.com/b-pass/plugin.video.the-chosen/assets/1461088/b395ca02-76c1-4569-b61d-5f7ee639af83)

**Comment by b-pass** [comment]
The new version I posted, 0.4.2, will let you login through kodi to view the locked ones.  Maybe try installing 0.4.2?

In the English version of kodi the error reads "check the log for more information".  If you're able to do that then that would help a lot to figure out what's gone wrong.... it would probably be in /tmp/kodi.log on this machine.  But if you don't know how then just installing the newer release is probably you best bet.

**Comment by LuisLlana** [comment]
No it does not work. I have the kodi.log output:

2024-06-17 16:52:08.351 T:1565     INFO <general>: initializing python engine.
2024-06-17 16:52:08.656 T:1413  WARNING <general>: CPythonInvoker(18, /storage/.kodi/addons/metadata.tvshows.themoviedb.org.python/main.py): the python script "/storage/.kodi/addons/metadata.tvshows.themoviedb.org.python/main.py" has left several classes in memory that we couldn't clean up. The classes include: N9XBMCAddon9xbmcaddon5AddonE
2024-06-17 16:52:08.656 T:1413     INFO <general>: Python interpreter stopped
2024-06-17 16:52:09.098 T:1565     INFO <general>: Skipped 9 duplicate messages..
2024-06-17 16:52:09.098 T:1565     INFO <general>: the-chosen : action=None
2024-06-17 16:52:09.416 T:1565    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'AttributeError'>
                                                   Error Contents: 'xbmc.InfoTagVideo' object has no attribute 'setTitle'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.video.the-chosen/addon.py", line 305, in <module>
                                                       list_page('main', None, None)
                                                     File "/storage/.kodi/addons/plugin.video.the-chosen/addon.py", line 104, in list_page
                                                       info.setTitle(kn)
                                                   AttributeError: 'xbmc.InfoTagVideo' object has no attribute 'setTitle'
                                                   -->End of Python script error report<--
                                                   
2024-06-17 16:52:09.748 T:1565     INFO <general>: Python interpreter stopped
2024-06-17 16:52:09.758 T:1563    ERROR <general>: GetDirectory - Error getting plugin://plugin.video.the-chosen/
2024-06-17 16:52:09.780 T:850     ERROR <general>: CGUIMediaWindow::GetDirectory(plugin://plugin.video.the-chosen/) failed

**Comment by b-pass** [comment]
Ah, I see.  Sorry for the confusion.  This is caused by an incompatibility with Kodi v19. Since that's now 3 versions behind, I don't think I can easily fix it.  If you want to use this addon, you'll have to upgrade your kodi to 20+ (or LibreELEC 11+).

I will change the addon.xml so that the addon will not install on v19 so no one else gets confused.  Sorry I can't support it, kodi completely changed how menu item labels work in 20+.

**Comment by LuisLlana** [comment]
Thank you. I will try to upgrade kodi.
